name: test-linux-venv

on:
  pull_request:
  push:
    branches: master

jobs:
  test-windows:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m venv env
        source env/bin/activate
        pip install .
    - name: test
      run: |
        ls
        source env/bin/activate
        python -m unittest discover
